const DoctorsAPI = [
  { id: 1, name: 'Dr. John Smith', label: 'Dr. John Smith', expertise: 'Cardiologist', city: 'New York' },
  { id: 2, name: 'Dr. Emily Johnson', label: 'Dr. Emily Johnson', expertise: 'Orthopedic Surgeon', city: 'Los Angeles' },
  { id: 3, name: 'Dr. Michael Davis', label: 'Dr. Michael Davis', expertise: 'Dermatologist', city: 'Chicago' },
  { id: 4, name: 'Dr. Sarah Wilson', label: 'Dr. Sarah Wilson', expertise: 'Pediatrician', city: 'Miami' },
  { id: 5, name: 'Dr. Andrew Miller', label: 'Dr. Andrew Miller', expertise: 'Neurologist', city: 'Miami' },
  { id: 6, name: 'Dr. Jessica Brown', label: 'Dr. Jessica Brown', expertise: 'Gynecologist', city: 'San Francisco' },
  { id: 7, name: 'Dr. Brian Lee', label: 'Dr. Brian Lee', expertise: 'Ophthalmologist', city: 'Chicago' },
  { id: 8, name: 'Dr. Olivia Clark', label: 'Dr. Olivia Clark', expertise: 'Psychiatrist', city: 'Boston' },
  { id: 9, name: 'Dr. Daniel Taylor', label: 'Dr. Daniel Taylor', expertise: 'Endocrinologist', city: 'Chicago' },
  { id: 10, name: 'Dr. Megan White', label: 'Dr. Megan White', expertise: 'Urologist', city: 'Atlanta' },
  { id: 11, name: 'Dr. James Carter', label: 'Dr. James Carter', expertise: 'Cardiologist', city: 'New York' },
  { id: 12, name: 'Dr. Lauren Williams', label: 'Dr. Lauren Williams', expertise: 'Orthopedic Surgeon', city: 'Los Angeles' },
  { id: 13, name: 'Dr. Christopher Evans', label: 'Dr. Christopher Evans', expertise: 'Dermatologist', city: 'Chicago' },
  { id: 14, name: 'Dr. Emily Turner', label: 'Dr. Emily Turner', expertise: 'Pediatrician', city: 'Chicago' },
  { id: 15, name: 'Dr. Samuel Harris', label: 'Dr. Samuel Harris', expertise: 'Neurologist', city: 'Miami' },
  { id: 16, name: 'Dr. Sophia Walker', label: 'Dr. Sophia Walker', expertise: 'Gynecologist', city: 'San Francisco' },
  { id: 17, name: 'Dr. Richard Martin', label: 'Dr. Richard Martin', expertise: 'Ophthalmologist', city: 'Chicago' },
  { id: 18, name: 'Dr. Victoria Turner', label: 'Dr. Victoria Turner', expertise: 'Psychiatrist', city: 'Boston' },
  { id: 19, name: 'Dr. Benjamin Young', label: 'Dr. Benjamin Young', expertise: 'Endocrinologist', city: 'Chicago' },
  { id: 20, name: 'Dr. Rachel Parker', label: 'Dr. Rachel Parker', expertise: 'Urologist', city: 'Chennai' },
   { id: 21, name: 'Dr. Rajesh Kumar', label: 'Dr. Rajesh Kumar', expertise: 'Cardiologist', city: 'Delhi' },
  { id: 22, name: 'Dr. Anjali Gupta', label: 'Dr. Anjali Gupta', expertise: 'Orthopedic Surgeon', city: 'Mumbai' },
  { id: 23, name: 'Dr. Sunil Sharma', label: 'Dr. Sunil Sharma', expertise: 'Dermatologist', city: 'Bangalore' },
  { id: 24, name: 'Dr. Aisha Patel', label: 'Dr. Aisha Patel', expertise: 'Pediatrician', city: 'Hyderabad' },
  { id: 25, name: 'Dr. Arjun Reddy', label: 'Dr. Arjun Reddy', expertise: 'Neurologist', city: 'Chennai' },
  { id: 26, name: 'Dr. Priya Singh', label: 'Dr. Priya Singh', expertise: 'Gynecologist', city: 'Bangalore' },
  { id: 27, name: 'Dr. Karthik Nair', label: 'Dr. Karthik Nair', expertise: 'Ophthalmologist', city: 'Delhi' },
  { id: 28, name: 'Dr. Vikram Malhotra', label: 'Dr. Vikram Malhotra', expertise: 'Psychiatrist', city: 'Mumbai' },
  { id: 29, name: 'Dr. Nandini Joshi', label: 'Dr. Nandini Joshi', expertise: 'Endocrinologist', city: 'Hyderabad' },
  { id: 30, name: 'Dr. Sameer Kapoor', label: 'Dr. Sameer Kapoor', expertise: 'Urologist', city: 'Chennai' },
  { id: 31, name: 'Dr. Priyanka Yadav', label: 'Dr. Priyanka Yadav', expertise: 'Cardiologist', city: 'Mumbai' },
  { id: 32, name: 'Dr. Rohit Sharma', label: 'Dr. Rohit Sharma', expertise: 'Orthopedic Surgeon', city: 'Delhi' },
  { id: 33, name: 'Dr. Maya Reddy', label: 'Dr. Maya Reddy', expertise: 'Dermatologist', city: 'Bangalore' },
  { id: 34, name: 'Dr. Anil Patel', label: 'Dr. Anil Patel', expertise: 'Pediatrician', city: 'Hyderabad' },
  { id: 35, name: 'Dr. Divya Mehra', label: 'Dr. Divya Mehra', expertise: 'Neurologist', city: 'Chennai' },
  { id: 36, name: 'Dr. Rahul Kapoor', label: 'Dr. Rahul Kapoor', expertise: 'Gynecologist', city: 'Bangalore' },
  { id: 37, name: 'Dr. Seema Gupta', label: 'Dr. Seema Gupta', expertise: 'Ophthalmologist', city: 'Delhi' },
  { id: 38, name: 'Dr. Anish Singh', label: 'Dr. Anish Singh', expertise: 'Psychiatrist', city: 'Mumbai' },
  { id: 39, name: 'Dr. Preeti Sharma', label: 'Dr. Preeti Sharma', expertise: 'Endocrinologist', city: 'Hyderabad' },
  { id: 40, name: 'Dr. Siddharth Verma', label: 'Dr. Siddharth Verma', expertise: 'Urologist', city: 'Chennai' }
];

export default DoctorsAPI;
